from __future__ import annotations

import csv
from pathlib import Path
from typing import Any


class CandidateLedger:
    """Point-in-time ledger of every primary long candidate generated by a signal engine.

    Records entry timestamp, feature vector, meta-probability, size, and exit outcome.
    Flushes to ``run_dir/artifacts/candidates.csv`` at the end of a run.
    """

    def __init__(self, run_dir: Path, feat_cols: list[str]) -> None:
        self.run_dir = Path(run_dir)
        self.feat_cols = list(feat_cols)
        self._base_cols = [
            "timestamp",
            "code",
            "entry_px",
            "meta_proba",
            "adj_proba",
            "meta_sz",
            "feat_m",
            "raw_size",
            "final_size",
            "passed",
            "exit_px",
            "exit_timestamp",
            "exit_reason",
            "return_pct",
            "realized_r",
            "label",
        ]
        self._feat_cols_safe = [
            f"f_{c.strip().replace(' ', '_').replace('/', '_').replace(':', '_')}"
            for c in self.feat_cols
        ]
        self.records: list[dict[str, Any]] = []
        self._open_by_code: dict[str, dict[str, Any]] = {}

    def record_entry(
        self,
        timestamp: Any,
        code: str,
        entry_px: float,
        features: list[float],
        meta_proba: float,
        adj_proba: float,
        meta_sz: float,
        feat_m: float,
        raw_size: float,
        final_size: float,
        passed: bool,
    ) -> dict[str, Any]:
        """Record a primary candidate event."""
        rec: dict[str, Any] = {
            "timestamp": timestamp,
            "code": code,
            "entry_px": _coerce(entry_px),
            "meta_proba": _coerce(meta_proba),
            "adj_proba": _coerce(adj_proba),
            "meta_sz": _coerce(meta_sz),
            "feat_m": _coerce(feat_m),
            "raw_size": _coerce(raw_size),
            "final_size": _coerce(final_size),
            "passed": 1 if passed else 0,
            "exit_px": "",
            "exit_timestamp": "",
            "exit_reason": "",
            "return_pct": "",
            "realized_r": "",
            "label": "",
        }
        for c, v in zip(self._feat_cols_safe, features):
            rec[c] = _coerce(v)
        self.records.append(rec)
        if passed:
            self._open_by_code[code] = rec
        return rec

    def record_exit(
        self,
        timestamp: Any,
        code: str,
        exit_px: float,
        reason: str = "",
    ) -> None:
        """Close the last open candidate for ``code`` with an exit."""
        rec = self._open_by_code.get(code)
        if rec is None:
            return
        rec["exit_px"] = _coerce(exit_px)
        rec["exit_timestamp"] = timestamp
        rec["exit_reason"] = reason
        entry_px = rec.get("entry_px")
        if entry_px not in (None, "", 0) and exit_px:
            try:
                rec["return_pct"] = (float(exit_px) - float(entry_px)) / float(entry_px)
                rec["realized_r"] = rec["return_pct"]
                rec["label"] = 1 if rec["realized_r"] > 0 else 0
            except Exception:
                rec["return_pct"] = ""
        self._open_by_code.pop(code, None)

    def flush(self) -> Path | None:
        """Write accumulated records to disk."""
        if not self.records:
            return None
        out = self.run_dir / "artifacts" / "candidates.csv"
        out.parent.mkdir(parents=True, exist_ok=True)
        fieldnames = self._base_cols + self._feat_cols_safe
        with out.open("w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
            writer.writeheader()
            writer.writerows(self.records)
        return out


def _coerce(v: Any) -> Any:
    """Make a value CSV-safe; blank out NaN."""
    if v is None:
        return ""
    try:
        if v != v:  # NaN
            return ""
        return v
    except Exception:
        return ""
